/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Demo;

import java.awt.Color;

public class Tank extends javax.swing.JFrame implements Observer{

    public Tank() {
        initComponents();
        setTitle("Tank");
        btnShoot.setEnabled(false);
        btnMissile.setEnabled(false);
        btnRedar.setEnabled(false);
        btnRotate.setEnabled(false);
        setLocation(10, 440);
        getContentPane().setBackground(Color.BLACK);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelArea = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        btnRedar = new javax.swing.JButton();
        btnRotate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 584, 369));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 584, 369));
        setMaximumSize(new java.awt.Dimension(584, 369));
        setMinimumSize(new java.awt.Dimension(584, 369));
        setPreferredSize(new java.awt.Dimension(584, 369));
        setSize(new java.awt.Dimension(584, 369));
        getContentPane().setLayout(null);

        jLabelArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelArea.setForeground(new java.awt.Color(212, 43, 43));
        jLabelArea.setText("Area Not Cleared");
        getContentPane().add(jLabelArea);
        jLabelArea.setBounds(15, 10, 117, 20);

        btnShoot.setBackground(new java.awt.Color(255, 51, 51));
        btnShoot.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnShoot.setText("Shoot");
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });
        getContentPane().add(btnShoot);
        btnShoot.setBounds(15, 40, 129, 35);

        btnMissile.setBackground(new java.awt.Color(255, 51, 51));
        btnMissile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMissile.setText("Missile Operation");
        getContentPane().add(btnMissile);
        btnMissile.setBounds(150, 40, 129, 35);

        btnRedar.setBackground(new java.awt.Color(255, 51, 51));
        btnRedar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRedar.setText("Redar operation");
        getContentPane().add(btnRedar);
        btnRedar.setBounds(15, 81, 129, 35);

        btnRotate.setBackground(new java.awt.Color(255, 51, 51));
        btnRotate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRotate.setText("Rotate Shooting");
        getContentPane().add(btnRotate);
        btnRotate.setBounds(150, 81, 129, 35);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ammo Count");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 49, 70, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Soldier Count");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 20, 72, 16);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(400, 20, 48, 20);
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(400, 50, 48, 20);

        jSlider1.setBackground(new java.awt.Color(204, 255, 255));
        jSlider1.setForeground(new java.awt.Color(102, 255, 255));
        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(100);
        jSlider1.setMaximumSize(new java.awt.Dimension(74, 312));
        jSlider1.setMinimumSize(new java.awt.Dimension(74, 312));
        jSlider1.setPreferredSize(new java.awt.Dimension(74, 312));
        getContentPane().add(jSlider1);
        jSlider1.setBounds(470, 14, 74, 300);

        jTextArea1.setBackground(new java.awt.Color(66, 118, 118));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 230, 140);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        getContentPane().add(btnSend);
        btnSend.setBounds(370, 280, 56, 35);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 280, 320, 35);

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(102, 255, 255));
        jCheckBox1.setText("Position");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(320, 70, 110, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Demo/wartank.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 584, 369);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        Observerble.getReference().getMessage("Tank:"+jTextField1.getText()+"\n");
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShootActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnRedar;
    private javax.swing.JButton btnRotate;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPosition(int value) {
        if(jCheckBox1.isSelected()){
            if(value >= 20){
                btnShoot.setEnabled(true);
            }
            if(value >= 40){
                btnMissile.setEnabled(true);
            }
            if(value >= 60){
                btnRedar.setEnabled(true);
            }
            if(value >= 80){
                btnRotate.setEnabled(true);
            }
            if(value <= 20){
                btnShoot.setEnabled(false);
            }
            if(value <= 40){
                btnMissile.setEnabled(false);
            }
            if(value <= 60){
                btnRedar.setEnabled(false);
            }
            if(value <= 80){
                btnRotate.setEnabled(false);
            }
        }
    }

    @Override
    public void setArea(boolean b) {
        if(b){
            jLabelArea.setText("Area Cleared");
        }else{
            jLabelArea.setText("Area Not Cleared");
        }
    }

    @Override
    public void setMessage(String msg) {
        jTextArea1.append(msg);
    }
}
